### PR TITLE
added support for manual workflow triggering

### PR DESCRIPTION
**Pull request by ujinjinjin**
removed trigger from changes on workflow .yml files and added manual trigger

### CODE REVIEW

**Comment by sebas77** [comment]
do you think manual is better? I didn't mean that the original rules were bad. I would mean that every time I change version.json both packages build, it's not a bad thing is it?

**Comment by ujinjinjin** [comment]
changes to version.json will still trigger both workflows to run, didn't change that. I removed trigger from changes to files in `.github/workflows/` to prevent unnecessary runs when workflow files are changed but package version is not

**Comment by sebas77** [comment]
strangely this is not merged yet, is it something outdated I forgot of or I still have to merge?

**Comment by ujinjinjin** [comment]
sorry, just noticed your comment here. It would be better to merge it, we added manual triggering to Svelto.ECS only and would be better to have them here too I think

**Comment by sebas77** [comment]
let me understand, if I start the svelto.ecs manual trigger, it won't trigger common?

**Comment by ujinjinjin** [comment]
Absolutely right

**Pull request merged**
